# Generated by Django 4.2.6 on 2023-10-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='has_consultant',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'yes'), (2, 'no')], null=True),
        ),
    ]
