# Generated by Django 4.2.6 on 2023-11-04 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0004_alter_institutelesson_student_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='staff_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.staffs'),
        ),
        migrations.AlterField(
            model_name='institutelesson',
            name='has_test_in_class',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='schoollesson',
            name='has_test_in_class',
            field=models.CharField(max_length=5),
        ),
    ]
